---
title: "FAQ"
---

<!--
## What's this class all about?

This class introduces methods, tools, and software for reproducibly managing, manipulating, analyzing, and visualizing large-scale biomedical data. Specifically, the course introduces the R statistical computing environment and packages for manipulating and visualizing high-dimensional data, covers strategies for reproducible research, and culminates with analysis of data from a real RNA-seq experiment using R and Bioconductor packages.

**_It's not a statistics class_**. Although we'll probably do some modeling and hypothesis testing, and talk a bit about design, statistics isn't the focus if this class. On a 1 to 10 scale of _theory_ to _practice_, this course sits at about an 8.
-->

## What are the pre-requisites?

_It depends on the class_. The introductory courses don't assume any knowledge of programming or using a command-line interface, but if you've ever had any experience here, the content won't come as so much of a shock. But _don't panic._ Command-line interfaces and programming languages like R are _incredibly powerful_ and will be utterly transformative on your research. There's a learning curve, and it's near-vertical in the beginning, but it's surmountable and the payoff is worth it! Some general knowledge of statistics and study design is helpful, but isn't strictly required.

The later classes in the R series (manipulation, tidy data, visualization, RNA-seq, statistics, TCGA, Bioconductor, etc.) All require a working knowledge of R, dplyr, and ggplot2.

## Do I need a laptop?

**YES.** You must have access to a computer on which you can install software. The class will be a mix of lecture, discussion, but primarily live coding. You must bring your laptop to the course every day. Bring your charging cable also.

## What software do I need?

All the software we're using in class is open-source and freely available online. This setup must be completed _prior to class_, as we will not have time for troubleshooting software installation issues during class. See the [setup instructions](setup.html), follow the directions for the class you're taking, and contact me if you have any real trouble.

<!-- 
## Can I audit this course?

Yes! However, **_you will be expected to attend every class meeting, participate in coding exercises during class, and complete any and all assignments_**, just as if you are taking the course for credit. 

**_UPDATE Feb 9 2016_**: The class is currently full.

[Click here to register to request to audit](https://docs.google.com/forms/d/1tHO-X4DupnHgIEsUei0K3kX5_UfLRK-y2KfxmxC6Ux0/viewform). The first day of the course is Monday, Feb 15, 2016. One week prior to the course starting, I will allow anyone who's requested to audit into the course, giving priority to people registering for credit. There are still plenty of seats open, so good chances you'll be able to get in.
-->

## Where will the class meet?

Carter Classroom, Health Sciences Library room 1211. This is downstairs one floor to the right (across the hall from Stephen Turner's office).

## Where do I get more help?

Glad you asked! [See here](help.html).

## I'm looking for the old course website.

- The course website from 2014-2015 is here: [bioconnector.github.io/workshops2015](http://bioconnector.github.io/workshops2015/).